- name: add MongoDB official repository for CentOS
  copy: src=../files/mongodb-org-3.0.repo dest=/etc/yum.repos.d/mongodb-org-3.0.repo

- block:
  - name: install MongoDB with specific version
    yum: name="mongodb-org-{{ mongodb_version }}*"  update_cache=yes  state=present
    yum: name="mongodb-org-shell-{{ mongodb_version }}*"  state=present
    yum: name="mongodb-org-tools-{{ mongodb_version }}*"  state=present
    when: mongodb_version is defined

  - name: install MongoDB with default version
    yum: name=mongodb-org  state=present
    when: mongodb_version is not defined