# file: roles/mysql/tasks/install.yml

- name: MySql packages are installed
  yum: pkg={{ item }}
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

- name: Start the MySQL service
  service: name=mariadb state=started enabled=true
